// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFdqZ3MJxmyIuyREEVnFf7a2QvDLlTScM',
    appId: '1:451137683135:web:296b4d191df033708c100a',
    messagingSenderId: '451137683135',
    projectId: 'vista-9aae7',
    authDomain: 'vista-9aae7.firebaseapp.com',
    storageBucket: 'vista-9aae7.firebasestorage.app',
    measurementId: 'G-525DMP2TQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2mzspLZZ-RcUC_qX03sI3lW-c1N6bjwE',
    appId: '1:451137683135:android:72c2edbda8ef2da38c100a',
    messagingSenderId: '451137683135',
    projectId: 'vista-9aae7',
    storageBucket: 'vista-9aae7.firebasestorage.app',
  );
}
